server:
  port: 8080
  metrics_port: 9090
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: postgres
  port: 5432
  user: espm
  password: espm123
  name: espm
  ssl_mode: disable
  max_connections: 50
  max_idle_connections: 10
  connection_lifetime: 1h

redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_conn_age: 1h

logging:
  level: info
  format: json
  output: stdout

metrics:
  enabled: true
  path: /metrics
  namespace: espm
  subsystem: event_publisher

tracing:
  enabled: true
  service_name: event-publisher
  exporter: jaeger
  endpoint: http://jaeger:14268/api/traces
  sampling_ratio: 1.0 