apiVersion: v1
kind: Service
metadata:
  name: command-api
  labels:
    app: espm
    component: command-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    app: espm
    component: command-api 