version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: espm-postgres
    environment:
      POSTGRES_USER: espm
      POSTGRES_PASSWORD: espm123
      POSTGRES_DB: espm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U espm"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: espm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@espm.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: 