server:
  port: 8081
  metrics_port: 9091
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: postgres
  port: 5432
  user: espm
  password: espm123
  name: espm
  ssl_mode: disable
  max_connections: 50
  max_idle_connections: 10
  connection_lifetime: 1h

redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_conn_age: 1h

kafka:
  brokers:
    - kafka:9092
  topic: events
  group_id: event-processor
  auto_offset_reset: earliest
  enable_auto_commit: true
  auto_commit_interval: 5s
  max_poll_records: 100
  max_poll_interval: 5m
  session_timeout: 30s
  heartbeat_interval: 10s

logging:
  level: info
  format: json
  output: stdout

metrics:
  enabled: true
  path: /metrics
  namespace: espm
  subsystem: event_processor

tracing:
  enabled: true
  service_name: event-processor
  exporter: jaeger
  endpoint: http://jaeger:14268/api/traces
  sampling_ratio: 1.0 