global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'espm-services'
    static_configs:
      - targets:
        - 'command-api:9090'
        - 'event-publisher:9090'
        - 'projections:9090'
        - 'query-api:9090'
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] 